;; -*- lexical-binding: t; -*-

(deftheme nn-world)

(defun nn-world-reload ()
  (interactive)
  (disable-theme 'nn-world)
  (load-theme 'nn-world t))

(let ((bg           "#1d1d1d")
      (panel        "#2d2d2d")
      (dim          "#6a6a6a")
      (border       "#404040")
      (hover        "#4a4a4a")
      (selection    "#555555")
      (subtle       "#857b6f")
      (border       "#3c3c3c")
      (fg           "#cccccc")
      (secondary    "#a8a8a8")
      (tertiary     "#808080")
      (pink         "#f5bde6")
      (red          "#f38ba8")
      (orange       "#f5a97f")
      (yellow       "#eed49f")
      (green        "#a6da95")
      (teal         "#4ec9b0")
      (blue         "#8aadf4")
      (purple       "#b180d7")
      (gold         "#b8860b")
      (black        "#000000")
      (white        "#ffffff")
      (match-fg     "#181818")
      (red-muted    "#ed8796")
      (red-dark     "#f44747")
      (red-deep     "#5a1d1d")
      (yellow-dark  "#eecc00")
      (green-muted  "#52ab52")
      (green-dark   "#3a5a3a")
      (green-deep   "#2a4a2a")
      (blue-muted   "#6a94d0"))
  (custom-theme-set-faces
   'nn-world
   `(success        ((t :bold t :foreground ,green)))
   `(warning        ((t :foreground ,yellow)))
   `(error          ((t :foreground ,red)))
   `(highlight      ((t :background ,selection)))
   `(lazy-highlight ((t :background ,dim :extend t)))
   `(match          ((t :foreground ,match-fg :background ,red)))
   `(shadow         ((t :foreground ,dim)))

   `(default             ((t :background ,bg :foreground ,fg :position t)))
   `(fringe              ((t :background ,bg)))
   `(button              ((t :foreground ,pink :underline nil)))
   `(secondary-selection ((t :background ,hover :foreground ,fg)))
   `(mode-line           ((t :background ,panel :foreground ,fg)))
   `(mode-line-inactive  ((t :background ,panel :foreground ,subtle)))
   `(minibuffer-prompt   ((t :foreground ,pink)))
   `(escape-glyph        ((t :foreground ,yellow)))
   `(header-line         ((t :background ,panel :foreground ,fg)))
   `(homoglyph           ((t :foreground ,yellow)))
   `(help-key-binding    ((t :background ,panel :foreground ,fg)))
   `(tooltip             ((t :background ,panel
                             :foreground ,fg
                             :box (:line-width 5 :color ,border))))

   `(cursor         ((t :background ,pink :foreground ,black)))
   `(mc/cursor-face ((t :inherit cursor)))
   `(region         ((t :inherit highlight)))

   `(font-lock-bracket-face              ((t :foreground ,fg)))
   `(font-lock-builtin-face              ((t :foreground ,red)))
   `(font-lock-comment-face              ((t :foreground ,green-muted)))
   `(font-lock-comment-delimiter-face    ((t :inherit font-lock-comment-face)))
   `(font-lock-constant-face             ((t :foreground ,yellow)))
   `(font-lock-delimiter-face            ((t :foreground ,fg)))
   `(font-lock-escape-face               ((t :foreground ,secondary)))
   `(font-lock-function-call-face        ((t :foreground ,fg :inherit italic)))
   `(font-lock-function-name-face        ((t :foreground ,fg :inherit italic)))
   `(font-lock-keyword-face              ((t :foreground ,pink :inherit italic)))
   `(font-lock-negation-char-face        ((t :foreground ,blue)))
   `(font-lock-number-face               ((t :foreground ,orange)))
   `(font-lock-operator-face             ((t :foreground ,blue)))
   `(font-lock-preprocessor-face         ((t :foreground ,secondary)))
   `(font-lock-property-name-face        ((t :foreground ,fg)))
   `(font-lock-reference-face            ((t :foreground ,secondary)))
   `(font-lock-regexp-grouping-backslash ((t :foreground ,orange)))
   `(font-lock-regexp-grouping-construct ((t :foreground ,orange)))
   `(font-lock-string-face               ((t :foreground ,green)))
   `(font-lock-type-face                 ((t :foreground ,purple :inherit italic)))
   `(font-lock-variable-name-face        ((t :foreground ,fg)))
   `(font-lock-variable-use-face         ((t :foreground ,fg)))
   `(font-lock-warning-face              ((t :inherit warning)))

   `(link         ((t :underline t)))
   `(link-visited ((t :inherit default :underline t)))

   `(line-number              ((t :foreground ,tertiary)))
   `(line-number-current-line ((t :foreground ,pink)))

   `(show-paren-match            ((t :box (:line-width (-1 . -1) :color ,pink) :weight bold)))
   `(show-paren-match-expression ((t :inherit match)))
   `(show-paren-mismatch         ((t :inherit warning)))

   `(isearch      ((t :inherit match :weight bold)))
   `(isearch-fail ((t :inherit error)))

   `(whitespace-big-indent       ((t :foreground ,orange)))
   `(whitespace-empty            ((t :inherit warning)))
   `(whitespace-indentation      ((t :foreground ,panel)))
   `(whitespace-line             ((t :underline (:style wave :color ,gold))))
   `(whitespace-newline          ((t :inherit shadow)))
   `(whitespace-space            ((t :inherit (shadow italic))))
   `(whitespace-space-after-tab  ((t :inherit warning)))
   `(whitespace-space-before-tab ((t :inherit warning)))
   `(whitespace-tab              ((t :inherit whitespace-newline)))
   `(whitespace-trailing         ((t :foreground ,orange :background ,orange)))
   `(trailing-whitespace         ((t :inherit whitespace-trailing)))

   `(flymake-error   ((t :underline (:style line :color ,red-dark))))
   `(flymake-warning ((t :underline (:style line :color ,yellow-dark))))
   `(flymake-note    ((t :underline (:style line :color ,green))))

   `(eglot-diagnostic-tag-deprecated-face  ((t :foreground ,red :strike-through t)))
   `(eglot-diagnostic-tag-unnecessary-face ((t :foreground ,tertiary :inherit flymake-warning)))
   `(eglot-highlight-symbol-face           ((t :inherit lazy-highlight)))
   `(eglot-inlay-hint-face                 ((t :foreground ,green-dark :height 0.9 :italic t)))
   `(eglot-parameter-hint-face             ((t :foreground ,teal)))
   `(eglot-type-hint-face                  ((t :foreground ,green)))

   `(compilation-error              ((t :foreground ,red-dark)))
   `(compilation-warning            ((t :foreground ,yellow-dark)))
   `(compilation-info               ((t :foreground ,green)))
   `(compilation-line-number        ((t :foreground ,yellow-dark)))
   `(compilation-column-number      ((t :foreground ,dim)))
   `(compilation-mode-line-exit     ((t :foreground ,green)))
   `(compilation-mode-line-fail     ((t :foreground ,red)))
   `(compilation-mode-line-run      ((t :foreground ,yellow-dark)))
   `(completions-annotations        ((t :foreground ,dim :italic t)))
   `(completions-common-part        ((t :foreground ,pink)))
   `(completions-first-difference   ((t :foreground ,pink)))
   `(completions-group-separator    ((t :foreground ,dim :strike-through t)))
   `(completions-group-title        ((t :foreground ,blue :bold t)))
   `(completions-highlight          ((t :background ,hover)))

   `(ido-first-match       ((t :foreground ,yellow)))
   `(ido-only-match        ((t :foreground ,green)))
   `(ido-subdir            ((t :inherit dired-directory)))
   `(ido-virtual           ((t :foreground ,blue)))
   `(ido-incomplete-regexp ((t :inherit warning)))
   `(ido-indicator         ((t :foreground ,fg :weight bold)))

   `(diff-header            ((t :foreground ,pink)))
   `(diff-hunk-header       ((t :foreground ,fg :background ,selection)))
   `(diff-added             ((t :background ,green-dark)))
   `(diff-removed           ((t :background ,red-dark)))
   `(diff-indicator-added   ((t :foreground ,green)))
   `(diff-indicator-removed ((t :foreground ,red)))
   `(diff-refine-added      ((t :background ,green-deep)))
   `(diff-refine-removed    ((t :background ,red-deep)))
   `(diff-refine-changed    ((t :background ,yellow :foreground ,bg)))

   `(eshell-ls-archive    ((t :foreground ,gold)))
   `(eshell-ls-backup     ((t :foreground ,yellow)))
   `(eshell-ls-clutter    ((t :foreground ,red :bold t)))
   `(eshell-ls-directory  ((t :foreground ,secondary :bold t)))
   `(eshell-ls-executable ((t :foreground ,green :bold t)))
   `(eshell-ls-missing    ((t :foreground ,red :bold t)))
   `(eshell-ls-product    ((t :foreground ,orange)))
   `(eshell-ls-readonly   ((t :foreground ,red)))
   `(eshell-ls-special    ((t :foreground ,pink :bold t)))
   `(eshell-ls-symlink    ((t :foreground ,blue :bold t)))
   `(eshell-prompt        ((t :foreground ,pink)))

   `(dired-flagged           ((t :foreground ,red :bold t)))
   `(dired-marked            ((t :bold t)))
   `(dired-mark              ((t :inherit dired-marked)))
   `(dired-header            ((t :foreground ,pink :bold t)))
   `(dired-ignored           ((t :foreground ,dim)))
   `(dired-special           ((t :foreground ,yellow)))
   `(dired-symlink           ((t :foreground ,pink)))
   `(dired-warning           ((t :inherit warning)))
   `(dired-directory         ((t :foreground ,secondary)))
   `(dired-perm-write        ((t :foreground ,green)))
   `(dired-broken-symlink    ((t :foreground ,fg :background ,red)))

   `(speedbar-button-face    ((t :foreground ,teal :bold t)))
   `(speedbar-directory-face ((t :inherit dired-directory)))
   `(speedbar-file-face      ((t :foreground ,fg)))
   `(speedbar-highlight-face ((t :background ,hover)))
   `(speedbar-selected-face  ((t :foreground ,pink :bold t :underline t)))
   `(speedbar-separator-face ((t :foreground ,border)))
   `(speedbar-tag-face       ((t :foreground ,yellow)))

   `(org-agenda-date-today         ((t :foreground ,secondary :bold t)))
   `(org-agenda-date-weekend       ((t :inherit org-agenda-date)))
   `(org-agenda-date-weekend-today ((t :inherit org-agenda-date :bold t)))
   `(org-agenda-dimmed-todo-face   ((t :inherit font-lock-comment-face)))
   `(org-agenda-done               ((t :foreground ,green)))
   `(org-agenda-structure          ((t :foreground ,secondary)))
   `(org-block                     ((t :extend t :background ,panel :foreground ,green)))
   `(org-block-begin-line          ((t :inherit org-meta-line :extend t :background ,panel)))
   `(org-block-end-line            ((t :inherit org-block-begin-line
                                       :extend t
                                       :background ,panel)))
   `(org-code                      ((t :foreground ,green)))
   `(org-column                    ((t :background ,panel)))
   `(org-column-title              ((t :inherit org-column :bold t :underline t)))
   `(org-date                      ((t :inherit org-agenda-date)))
   `(org-document-info             ((t :foreground ,blue)))
   `(org-document-info-keyword     ((t :inherit font-lock-comment-face)))
   `(org-document-title            ((t :bold t :foreground ,blue)))
   `(org-done                      ((t :inherit font-lock-comment-face)))
   `(org-ellipsis                  ((t :inherit font-lock-comment-face)))
   `(org-footnote                  ((t :foreground ,gold)))
   `(org-formula                   ((t :foreground ,pink)))
   `(org-headline-done             ((t :inherit org-done)))
   `(org-hide                      ((t :foreground ,panel :background ,bg)))
   `(org-indent                    ((t :foreground ,bg)))
   `(org-level-1                   ((t :inherit bold :foreground ,red)))
   `(org-level-2                   ((t :inherit bold :foreground ,orange)))
   `(org-level-3                   ((t :normal t :foreground ,yellow)))
   `(org-level-4                   ((t :normal t :foreground ,green)))
   `(org-level-5                   ((t :normal t :foreground ,blue)))
   `(org-level-6                   ((t :normal t :foreground ,purple)))
   `(org-level-7                   ((t :normal t :foreground ,gold)))
   `(org-level-8                   ((t :normal t :foreground ,red)))
   `(org-link                      ((t :inherit link)))
   `(org-meta-line                 ((t :inherit font-lock-comment-face)))
   `(org-mode-line-clock-overrun   ((t :inherit mode-line :foreground ,red)))
   `(org-priority                  ((t :foreground ,yellow)))
   `(org-quote                     ((t :extend t
                                       :background ,panel
                                       :foreground ,green
                                       :slant italic)))
   `(org-scheduled                 ((t :foreground ,green)))
   `(org-scheduled-previously      ((t :foreground ,teal)))
   `(org-scheduled-today           ((t :foreground ,green :bold t)))
   `(org-sexp-date                 ((t :foreground ,secondary)))
   `(org-special-keyword           ((t :inherit font-lock-keyword-face)))
   `(org-table                     ((t :foreground ,dim)))
   `(org-tag                       ((t :foreground ,gold :bold t)))
   `(org-todo                      ((t :foreground ,orange)))
   `(org-upcoming-deadline         ((t :foreground ,red)))
   `(org-verbatim                  ((t :inherit org-quote)))
   `(org-warning                   ((t :inherit warning)))

   `(message-header-to             ((t :foreground ,pink     :bold t)))
   `(message-header-cc             ((t :foreground ,blue     :bold t)))
   `(message-header-subject        ((t :foreground ,fg       :bold t :height 1.1)))
   `(message-header-newsgroups     ((t :foreground ,gold)))
   `(message-header-other          ((t :foreground ,tertiary)))
   `(message-header-name           ((t :foreground ,teal)))
   `(message-header-xheader        ((t :foreground ,purple)))
   `(message-separator             ((t :foreground ,border)))
   `(message-cited-text            ((t :foreground ,green-muted)))
   `(message-cited-text-1          ((t :foreground ,yellow)))
   `(message-cited-text-2          ((t :foreground ,orange)))
   `(message-cited-text-3          ((t :foreground ,purple)))
   `(message-cited-text-4          ((t :foreground ,blue-muted)))
   `(message-mml                   ((t :foreground ,pink)))

   `(gnus-header                 ((t :foreground ,pink     :bold t)))
   `(gnus-header-from            ((t :foreground ,pink     :bold t)))
   `(gnus-header-subject         ((t :foreground ,fg       :bold t)))
   `(gnus-header-newsgroups      ((t :foreground ,gold)))
   `(gnus-header-name            ((t :foreground ,teal)))
   `(gnus-header-content         ((t :foreground ,secondary)))
   `(gnus-summary-normal-unread  ((t :foreground ,pink     :bold t)))
   `(gnus-summary-normal-read    ((t :foreground ,dim)))
   `(gnus-summary-normal-ancient ((t :foreground ,tertiary)))
   `(gnus-summary-normal-ticked  ((t :foreground ,orange)))
   `(gnus-summary-high-unread    ((t :foreground ,pink     :bold t)))
   `(gnus-summary-high-read      ((t :foreground ,blue)))
   `(gnus-summary-high-ancient   ((t :foreground ,blue-muted)))
   `(gnus-summary-high-ticked    ((t :foreground ,yellow)))
   `(gnus-summary-low-unread     ((t :foreground ,green-muted)))
   `(gnus-summary-low-read       ((t :foreground ,dim)))
   `(gnus-summary-low-ancient    ((t :foreground ,dim)))
   `(gnus-summary-low-ticked     ((t :foreground ,green)))
   `(gnus-summary-selected       ((t :foreground ,fg :background ,selection :bold t)))
   `(gnus-summary-cancelled      ((t :foreground ,red-muted :strike-through t)))
   `(gnus-group-mail-1           ((t :foreground ,pink :bold t)))
   `(gnus-group-mail-2           ((t :foreground ,yellow :bold t)))
   `(gnus-group-mail-3           ((t :foreground ,blue-muted)))
   `(gnus-group-mail-4           ((t :foreground ,orange)))
   `(gnus-group-mail-5           ((t :foreground ,purple)))
   `(gnus-group-mail-6           ((t :foreground ,green)))
   `(gnus-group-mail-low         ((t :foreground ,dim)))
   `(gnus-group-mail-1-empty     ((t :foreground ,pink)))
   `(gnus-group-mail-2-empty     ((t :foreground ,yellow)))
   `(gnus-group-mail-3-empty     ((t :foreground ,blue-muted)))
   `(gnus-group-mail-4-empty     ((t :foreground ,orange)))
   `(gnus-group-mail-5-empty     ((t :foreground ,purple)))
   `(gnus-group-mail-6-empty     ((t :foreground ,green)))
   `(gnus-group-mail-low-empty   ((t :foreground ,dim)))
   `(gnus-group-news-1           ((t :foreground ,pink :bold t)))
   `(gnus-group-news-2           ((t :foreground ,yellow :bold t)))
   `(gnus-group-news-3           ((t :foreground ,blue-muted)))
   `(gnus-group-news-4           ((t :foreground ,orange)))
   `(gnus-group-news-5           ((t :foreground ,purple)))
   `(gnus-group-news-6           ((t :foreground ,green)))
   `(gnus-group-news-low         ((t :foreground ,dim)))
   `(gnus-server-opened          ((t :foreground ,green)))
   `(gnus-server-closed          ((t :foreground ,red-muted)))
   `(gnus-server-denied          ((t :foreground ,red)))
   `(gnus-server-offline         ((t :foreground ,dim)))
   `(gnus-server-agent           ((t :foreground ,blue)))
   `(gnus-server-cloud           ((t :foreground ,teal)))
   `(gnus-server-cloud-host      ((t :foreground ,blue-muted)))
   `(gnus-signature              ((t :foreground ,dim :slant italic)))
   `(gnus-button                 ((t :foreground ,blue :bold t :underline t)))
   `(gnus-emphasis-bold          ((t :bold t)))
   `(gnus-emphasis-italic        ((t :slant italic)))
   `(gnus-emphasis-underline     ((t :underline t)))
   `(gnus-splash                 ((t :foreground ,secondary)))

   `(ansi-color-black          ((t :foreground ,hover)))
   `(ansi-color-red            ((t :foreground ,red)))
   `(ansi-color-yellow         ((t :foreground ,yellow)))
   `(ansi-color-green          ((t :foreground ,green)))
   `(ansi-color-blue           ((t :foreground ,blue)))
   `(ansi-color-magenta        ((t :foreground ,pink)))
   `(ansi-color-cyan           ((t :foreground ,teal)))
   `(ansi-color-white          ((t :foreground ,tertiary)))
   `(ansi-color-bright-black   ((t :foreground ,selection)))
   `(ansi-color-bright-red     ((t :foreground ,red)))
   `(ansi-color-bright-yellow  ((t :foreground ,yellow)))
   `(ansi-color-bright-green   ((t :foreground ,green)))
   `(ansi-color-bright-blue    ((t :foreground ,blue)))
   `(ansi-color-bright-magenta ((t :foreground ,pink)))
   `(ansi-color-bright-cyan    ((t :foreground ,teal)))
   `(ansi-color-bright-white   ((t :foreground ,secondary)))

   `(markdown-blockquote-face         ((t :background ,red-deep
                                          :foreground ,green
                                          :inherit italic)))
   `(markdown-bold-face               ((t :bold t :foreground ,red)))
   `(markdown-italic-face             ((t :inherit italic :foreground ,secondary)))
   `(markdown-strike-through-face     ((t :strike-through t :foreground ,tertiary)))
   `(markdown-markup-face             ((t :foreground ,secondary)))
   `(markdown-inline-code-face        ((t :foreground ,green)))
   `(markdown-highlight-face          ((t :inherit highlight)))
   `(markdown-header-face             ((t :bold t :foreground ,secondary)))
   `(markdown-header-face-1           ((t :foreground ,red :bold t :height 1.4)))
   `(markdown-header-face-2           ((t :foreground ,orange :bold t :height 1.3)))
   `(markdown-header-face-3           ((t :foreground ,yellow :bold t :height 1.2)))
   `(markdown-header-face-4           ((t :foreground ,green :bold t :height 1.1)))
   `(markdown-header-face-5           ((t :foreground ,blue :bold t)))
   `(markdown-header-face-6           ((t :foreground ,purple :bold t)))
   `(markdown-header-delimiter-face   ((t :inherit markdown-header-face)))
   `(markdown-header-rule-face        ((t :foreground ,tertiary)))
   `(markdown-code-face               ((t :background ,panel :foreground ,secondary)))
   `(markdown-pre-face                ((t :background ,panel :foreground ,pink)))
   `(markdown-language-keyword-face   ((t :foreground ,pink)))
   `(markdown-language-info-face      ((t :foreground ,secondary)))
   `(markdown-link-face               ((t :foreground ,blue :underline t)))
   `(markdown-url-face                ((t :foreground ,blue :underline t)))
   `(markdown-plain-url-face          ((t :foreground ,blue :underline t)))
   `(markdown-link-title-face         ((t :foreground ,green)))
   `(markdown-missing-link-face       ((t :foreground ,red :underline t)))
   `(markdown-reference-face          ((t :foreground ,yellow)))
   `(markdown-list-face               ((t :foreground ,teal)))
   `(markdown-gfm-checkbox-face       ((t :foreground ,green)))
   `(markdown-table-face              ((t :foreground ,blue)))
   `(markdown-footnote-marker-face    ((t :foreground ,blue)))
   `(markdown-footnote-text-face      ((t :foreground ,purple)))
   `(markdown-metadata-key-face       ((t :foreground ,blue)))
   `(markdown-metadata-value-face     ((t :foreground ,green)))
   `(markdown-hr-face                 ((t :foreground ,subtle)))
   `(markdown-line-break-face         ((t :foreground ,dim)))
   `(markdown-comment-face            ((t :inherit font-lock-comment-face)))
   `(markdown-html-attr-name-face     ((t :foreground ,orange)))
   `(markdown-html-attr-value-face    ((t :foreground ,green)))
   `(markdown-html-entity-face        ((t :foreground ,orange)))
   `(markdown-html-tag-delimiter-face ((t :foreground ,pink)))
   `(markdown-html-tag-name-face      ((t :foreground ,pink)))
   `(markdown-math-face               ((t :foreground ,teal)))

   `(dape-breakpoint-face                ((t :foreground ,red-dark :bold t)))
   `(dape-breakpoint-until-face          ((t :foreground ,black :background ,yellow)))
   `(dape-exception-description-face     ((t :foreground ,red-dark)))
   `(dape-expression-face                ((t :foreground ,green)))
   `(dape-header-line-active-face        ((t :foreground ,pink :bold t)))
   `(dape-header-line-hover-face         ((t :foreground ,fg :background ,hover)))
   `(dape-header-line-inactive-face      ((t :foreground ,dim)))
   `(dape-hits-face                      ((t :foreground ,green :bold t)))
   `(dape-inlay-hint-face                ((t :foreground ,dim :background ,panel)))
   `(dape-inlay-hint-highlight-face      ((t :foreground ,blue :background ,hover :bold t)))
   `(dape-log-face                       ((t :foreground ,dim)))
   `(dape-minibuffer-hint-separator-face ((t :foreground ,border)))
   `(dape-repl-error-face                ((t :foreground ,red-dark)))
   `(dape-source-line-face               ((t :background ,red-deep)))

   `(corfu-default     ((t :background ,panel)))
   `(corfu-current     ((t :background ,hover)))
   `(corfu-bar         ((t :background ,secondary)))
   `(corfu-border      ((t :inherit corfu-default)))
   `(corfu-annotations ((t :inherit font-lock-comment-face)))
   `(corfu-deprecated  ((t :strike-through t)))

   `(nerd-icons-blue   ((t :foreground ,blue)))
   `(nerd-icons-purple ((t :foreground ,purple)))
   `(nerd-icons-pink   ((t :foreground ,pink)))
   `(nerd-icons-cyan   ((t :foreground ,teal)))
   `(nerd-icons-green  ((t :foreground ,green)))
   `(nerd-icons-silver ((t :foreground ,tertiary)))
   `(nerd-icons-lblue  ((t :foreground ,blue-muted)))
   `(nerd-icons-orange ((t :foreground ,orange)))

   `(rainbow-delimiters-depth-1-face   ((t :foreground ,yellow)))
   `(rainbow-delimiters-depth-2-face   ((t :foreground ,pink)))
   `(rainbow-delimiters-depth-3-face   ((t :foreground ,blue-muted)))
   `(rainbow-delimiters-depth-4-face   ((t :foreground ,orange)))
   `(rainbow-delimiters-depth-5-face   ((t :foreground ,purple)))
   `(rainbow-delimiters-depth-6-face   ((t :foreground ,green)))
   `(rainbow-delimiters-depth-7-face   ((t :foreground ,teal)))
   `(rainbow-delimiters-depth-8-face   ((t :foreground ,gold)))
   `(rainbow-delimiters-unmatched-face ((t :inherit warning)))

   `(eldoc-box-border ((t :background ,tertiary)))
   `(eldoc-box-body   ((t :foreground ,fg :background ,panel)))

   `(magit-branch-local                    ((t :foreground ,teal)))
   `(magit-branch-remote                   ((t :foreground ,green)))
   `(magit-tag                             ((t :foreground ,orange)))
   `(magit-section-heading                 ((t :foreground ,blue :bold t)))
   `(magit-section-highlight               ((t :background ,panel :extend t)))
   `(magit-diff-context-highlight          ((t :background ,panel :foreground ,fg :extend t)))
   `(magit-diff-revision-summary           ((t :foreground ,blue :bold t)))
   `(magit-diff-revision-summary-highlight ((t :foreground ,blue :weight bold)))
   `(magit-diff-added                      ((t :foreground ,green :extend t)))
   `(magit-diff-added-highlight            ((t :background ,hover :foreground ,green :extend t)))
   `(magit-diff-removed                    ((t :foreground ,red :extend t)))
   `(magit-diff-removed-highlight          ((t :background ,hover :foreground ,red :extend t)))
   `(magit-diff-file-heading               ((t :foreground ,fg)))
   `(magit-diff-file-heading-highlight     ((t :inherit magit-section-highlight)))
   `(magit-diffstat-added                  ((t :foreground ,green)))
   `(magit-diffstat-removed                ((t :foreground ,red)))
   `(magit-hash                            ((t :foreground ,secondary)))
   `(magit-diff-hunk-heading               ((t :inherit diff-hunk-header)))
   `(magit-diff-hunk-heading-highlight     ((t :inherit diff-hunk-header :bold t)))
   `(magit-log-author                      ((t :foreground ,secondary)))
   `(magit-process-ng                      ((t :foreground ,orange :bold t)))
   `(magit-process-ok                      ((t :foreground ,green :bold t)))) )

(provide-theme 'nn-world)
