;; -*- lexical-binding: t; -*-

(defun my-move-line-up ()
  (interactive)
  (transpose-lines 1)
  (forward-line -2))

(defun my-move-line-down ()
  (interactive)
  (forward-line 1)
  (transpose-lines 1)
  (forward-line -1))

(defun my-copy-line-and-move-down ()
  (interactive)
  (duplicate-line)
  (next-line 1))

(defun my-cut ()
  (interactive)
  (if (use-region-p)
      (kill-region (region-beginning) (region-end))
    (kill-whole-line)))

(defun my-copy ()
  (interactive)
  (if (use-region-p)
      (copy-region-as-kill (region-beginning) (region-end))
    (progn (kill-ring-save (line-beginning-position) (line-beginning-position 2)))))

(defun my-delete-whole-line-no-kill ()
  (interactive)
  (delete-region (line-beginning-position) (line-beginning-position 2)))

(defun my-kill ()
  (interactive)
  (when (and (buffer-modified-p)
             (buffer-file-name))
    (save-buffer))
  (kill-current-buffer))

(defun my-downcase-dwim ()
  (interactive)
  (if (use-region-p)
      (downcase-region (region-beginning) (region-end))
    (call-interactively #'downcase-word)))

(defun my-upcase-dwim ()
  (interactive)
  (if (use-region-p)
      (upcase-region (region-beginning) (region-end))
    (call-interactively #'upcase-word)))

(defun my-buffer-visible-p ()
  (let ((name (buffer-name)))
    (or (not (string-prefix-p "*" name))
        (string-prefix-p "*compilation" name)
        (string-prefix-p "*grep" name))))

(defun my-next-buffer ()
  (interactive)
  (next-buffer)
  (while (not (my-buffer-visible-p)) (next-buffer)))

(defun my-previous-buffer ()
  (interactive)
  (previous-buffer)
  (while (not (my-buffer-visible-p)) (previous-buffer)))

(defun my-delete-word-forward ()
  (interactive)
  (delete-region (point) (save-excursion (forward-word 1) (point))))

(defun my-delete-word-backward ()
  (interactive)
  (delete-region (point) (save-excursion (forward-word -1) (point))))

(defun my-home-dired ()
  (interactive)
  (find-file "~"))

(keymap-global-set "<escape>" #'keyboard-escape-quit)
(keymap-global-set "M-o" #'other-window)
(keymap-global-set "M-<up>" #'my-move-line-up)
(keymap-global-set "M-<down>" #'my-move-line-down)
(keymap-global-set "S-<tab>" #'indent-rigidly-left-to-tab-stop)
(keymap-global-set "C-<tab>" #'bs-cycle-next)
(keymap-global-set "C-S-<tab>" #'bs-cycle-previous)
(keymap-global-set "C-1" #'scroll-up-command)
(keymap-global-set "C-2" #'scroll-down-command)
(keymap-global-set "C-3" #'recenter-top-bottom)
(keymap-global-set "C-," #'my-copy-line-and-move-down)
(keymap-global-set "C-`" #'shell)
(keymap-global-set "C-:" #'shell-command)
(keymap-global-set "C-~" #'my-home-dired)
(keymap-global-set "C-c c" #'compile)
(keymap-global-set "C-c s" #'save-buffer)
(keymap-global-set "C-c S" #'save-some-buffers)
(keymap-global-set "C-c r" #'recentf-open-files)
(keymap-global-set "C-c p" #'bs-show)

(keymap-global-set "M-l" #'my-downcase-dwim)
(keymap-global-set "M-u" #'my-upcase-dwim)
(keymap-global-set "M-w" #'my-copy)
(keymap-global-set "C-<delete>" #'my-delete-word-forward)
(keymap-global-set "C-<backspace>" #'my-delete-word-backward)
(keymap-global-set "C-w" #'my-cut)
(keymap-global-set "C-a" #'back-to-indentation)
(keymap-global-set "C-S-s" #'isearch-backward)
(keymap-global-set "C-r" #'query-replace)
(keymap-global-set "C-S-r" #'query-replace-regexp)
(keymap-global-set "C-x w" #'delete-window)
(keymap-global-set "C-x S-<tab>" #'my-previous-buffer)
(keymap-global-set "C-x <tab>" #'my-next-buffer)
(keymap-global-set "C-x <left>"  #'my-previous-buffer)
(keymap-global-set "C-x <right>" #'my-next-buffer)
(keymap-global-set "C-x k" #'my-kill)
(keymap-global-set "C-x C-k" #'kill-buffer)
(keymap-global-set "C-x C-b" #'ibuffer)
(keymap-global-set "C-S-<backspace>" #'my-delete-whole-line-no-kill)
(keymap-global-set "C-M-<up>" #'windmove-up)
(keymap-global-set "C-M-<down>" #'windmove-down)
(keymap-global-set "C-M-<left>" #'windmove-left)
(keymap-global-set "C-M-<right>" #'windmove-right)

(provide 'init-keybind)
