;;; -*- lexical-binding: t -*-
(defun evil-forward-beginning (count word-chars non-word-chars)
  (dotimes (_ count)
    (skip-chars-forward "[:space:]")
    (when (eobp) (user-error "No next word"))
    (if (looking-at (format "[%s]" word-chars))
        (progn (skip-chars-forward word-chars)
               (skip-chars-forward "[:space:]"))
      (skip-chars-forward non-word-chars)
      (skip-chars-forward "[:space:]"))))

(defun evil-backward-beginning (count word-chars non-word-chars)
  (dotimes (_ count)
    (skip-chars-backward "[:space:]")
    (when (bobp) (user-error "No previous word"))
    (backward-char 1)
    (if (looking-at (format "[%s]" word-chars))
        (skip-chars-backward word-chars)
      (skip-chars-backward non-word-chars))))

(defun evil-forward-end (count word-chars non-word-chars)
  (dotimes (_ count)
    (skip-chars-forward "[:space:]")
    (when (eobp) (user-error "No next word"))
    (forward-char 1)
    (skip-chars-forward "[:space:]")
    (if (looking-at (format "[%s]" word-chars))
        (skip-chars-forward word-chars)
      (skip-chars-forward non-word-chars))
    (unless (bobp) (backward-char 1))))

(defun evil-backward-end (count word-chars non-word-chars)
  (dotimes (_ count)
    (skip-chars-backward "[:space:]")
    (when (bobp) (user-error "No previous word"))
    (backward-char 1)
    (if (looking-at (format "[%s]" word-chars))
        (skip-chars-backward word-chars)
      (skip-chars-backward non-word-chars))
    (skip-chars-backward "[:space:]")
    (unless (bobp)
      (backward-char 1)
      (if (looking-at (format "[%s]" word-chars))
          (skip-chars-backward word-chars)
        (skip-chars-backward non-word-chars)))
    (skip-chars-forward "[:space:]")
    (if (looking-at (format "[%s]" word-chars))
        (progn (skip-chars-forward word-chars) (backward-char 1))
      (progn (skip-chars-forward non-word-chars) (backward-char 1)))))

(defun evil-forward-word-begin (&optional count)
  (interactive "^p")
  (evil-forward-beginning (or count 1) "[:word:]" "^[:word:]\n\r\t\f "))

(defun evil-backward-word-begin (&optional count)
  (interactive "^p")
  (evil-backward-beginning (or count 1) "[:word:]" "^[:word:]\n\r\t\f "))

(defun evil-forward-word-end (&optional count)
  (interactive "^p")
  (evil-forward-end (or count 1) "[:word:]" "^[:word:]\n\r\t\f "))

(defun evil-backward-word-end (&optional count)
  (interactive "^p")
  (evil-backward-end (or count 1) "[:word:]" "^[:word:]\n\r\t\f "))

(defun evil-forward-WORD-begin (&optional count)
  (interactive "^p")
  (evil-forward-beginning (or count 1) "^\n\r\t\f " "^\n\r\t\f "))

(defun evil-backward-WORD-begin (&optional count)
  (interactive "^p")
  (evil-backward-beginning (or count 1) "^\n\r\t\f " "^\n\r\t\f "))

(defun evil-forward-WORD-end (&optional count)
  (interactive "^p")
  (evil-forward-end (or count 1) "^\n\r\t\f " "^\n\r\t\f "))

(defun evil-backward-WORD-end (&optional count)
  (interactive "^p")
  (evil-backward-end (or count 1) "^\n\r\t\f " "^\n\r\t\f "))

(defun my-delete-word-forward ()
  (interactive)
  (if (eolp) (unless (eobp) (delete-char 1))
    (let* ((s (point))
           (eol (line-end-position))
           (e (save-excursion
                (condition-case nil (evil-forward-word-begin) (error))
                (min (point) eol))))
      (when (> e s) (delete-region s e)))))

(defun my-delete-word-backward ()
  (interactive)
  (if (bolp) (if (bobp) (delete-char 1) (delete-char -1))
    (let* ((s (point))
           (bol (line-beginning-position))
           (e (save-excursion
                (condition-case nil (evil-backward-word-begin) (error))
                (max (point) bol))))
      (when (< e s) (delete-region e s)))))

(keymap-global-set "C-<delete>" #'my-delete-word-forward)
(keymap-global-set "C-<backspace>" #'my-delete-word-backward)
(keymap-global-set "M-f" #'evil-forward-word-begin)
(keymap-global-set "M-b" #'evil-backward-word-begin)
(keymap-global-set "C-<right>" #'evil-forward-word-begin)
(keymap-global-set "C-<left>" #'evil-backward-word-begin)
(keymap-global-set "C-S-<right>" #'evil-forward-word-begin)
(keymap-global-set "C-S-<left>" #'evil-backward-word-begin)
(keymap-global-set "C-M-f" #'evil-forward-word-end)
(keymap-global-set "C-M-b" #'evil-backward-word-end)
(keymap-global-set "C-M-<right>" #'evil-forward-word-end)
(keymap-global-set "C-M-<left>" #'evil-backward-word-end)
(keymap-global-set "M-F" #'evil-forward-WORD-begin)
(keymap-global-set "M-B" #'evil-backward-WORD-begin)
(keymap-global-set "C-M-F" #'evil-forward-WORD-end)
(keymap-global-set "C-M-B" #'evil-backward-WORD-end)

(provide 'init-evil)
